<html>
    <select name="acp_industry" id="acp_industry" onchange="checkSelectIndustry1();">
        <option value="">-Select Industry -</option>           
        <option value="Accounting/Taxation">Accounting/Taxation</option>
        <option value="Advertising/PR">Advertising/PR</option>
        <option value="Agriculture/Fertilizer/Pesticide">Agriculture/Fertilizer/Pesticide</option>
        <option value="Apparel/Clothing">Apparel/Clothing</option>
        <option value="Architecture/Interior Design">Architecture/Interior Design</option>
        <option value="Arts / Entertainment">Arts / Entertainment</option>
        <option value="AutoMobile"></option>
        <option value="Aviation">Aviation</option>
        <option value="Banking/Financial Services">Banking/Financial Services</option>
        <option value="BPO">BPO</option>
        <option value="Broadcasting">Broadcasting</option>
        <option value="Business Development">Business Development</option>
        <option value="Call Center">Call Center</option>
        <option value="Chemicals">Chemicals</option>
        <option value="Construction/Cement/Metals">Construction/Cement/Metals</option>
        <option value="Consultants">Consultants</option>
        <option value="Courier/Logistics">Courier/Logistics</option>
        <option value="Distribution and Logistics">Distribution and Logistics</option>
        <option value="Education/Training">Education/Training</option>
        <option value="Electronics">Electronics</option>
        <option value="Engineering">Engineering</option>
        <option value="Event Management">Event Management</option>
        <option value="Fashion">Fashion</option>
        <option value="Fast Moving Consumer Goods (FMCG)">Fast Moving Consumer Goods (FMCG)</option>
        <option value="Food &amp; Beverages">Food &amp; Beverages</option>
        <option value="Gems &amp; Jewelery">Gems &amp; Jewelery</option>
        <option value="Government">Government</option>
        <option value="Health &amp; Fitness">Health &amp; Fitness</option>
        <option value="Healthcare/Hospital/Medical">Healthcare/Hospital/Medical</option>
        <option value="Hospitality">Hospitality</option>
        <option value="Hotel Management / Restaurants">Hotel Management / Restaurants</option>
        <option value="Importers/ Distributors/Exporters">Importers/ Distributors/Exporters</option>
        <option value="Information Technology">Information Technology</option>
        <option value="Insurance / Takaful">Insurance / Takaful</option>
        <option value="Investments">Investments</option>
        <option value="Law Firms/Legal">Law Firms/Legal</option>
        <option value="Manufacturing">Manufacturing</option>
        <option value="Media/Communications">Media/Communications</option>
        <option value="Mining/Oil &amp; Gas/Petroleum">Mining/Oil &amp; Gas/Petroleum</option>
        <option value="N.G.O./Social Services">N.G.O./Social Services</option>
        <option value="Packaging">Packaging</option>
        <option value="Personal Care and Services">Personal Care and Services</option>
        <option value="Pharmaceuticals/Clinical Research">Pharmaceuticals/Clinical Research</option>
        <option value="Power/Energy">Power/Energy</option>
        <option value="Project Management">Project Management</option>
        <option value="Publishing/Printing">Publishing/Printing</option>
        <option value="Real Estate/Property">Real Estate/Property</option>
        <option value="Recruitment/Employment Firms">Recruitment/Employment Firms</option>
        <option value="Retail">Retail</option>
        <option value="Security/Law Enforcement">Security/Law Enforcement</option>
        <option value="Services">Services</option>
        <option value="Shipping/Marine">Shipping/Marine</option>
        <option value="Telecommunication/ISP">Telecommunication/ISP</option>
        <option value="Textiles/Garments">Textiles/Garments</option>
        <option value="Tiles &amp; Ceramics">Tiles &amp; Ceramics</option>
        <option value="Travel/Tourism/Transportation">Travel/Tourism/Transportation</option>
        <option value="Warehousing">Warehousing</option>                        
        <option value="Other">Other</option>
    </select>
</html>